<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AcfFieldsServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        if (! function_exists('acf_add_local_field_group')) {
            return;
        }

        add_action('acf/init', [$this, 'registerFieldGroups']);
    }

    /**
     * Register all ACF field groups for the front page.
     */
    public function registerFieldGroups(): void
    {
        acf_add_local_field_group([
            'key' => 'group_front_page',
            'title' => 'Front Page',
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'front-page.blade.php',
                    ],
                ],
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'front-page',
                    ],
                ],
            ],
            'menu_order' => 1,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'fields' => [
                // TAB: Contact Information
                [
                    'key' => 'tab_contact',
                    'label' => 'Contact Information',
                    'name' => 'tab_contact',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_contact_phone',
                    'label' => 'Phone Number',
                    'name' => 'contact_phone',
                    'type' => 'text',
                    'instructions' => 'Phone number displayed in header and contact sections',
                    'required' => 0,
                    'default_value' => '07555 641 081',
                ],
                [
                    'key' => 'field_contact_email',
                    'label' => 'Email Address',
                    'name' => 'contact_email',
                    'type' => 'email',
                    'instructions' => 'Email address displayed in header',
                    'required' => 0,
                    'default_value' => 'tomasz@emove-fs.co.uk',
                ],
                [
                    'key' => 'field_contact_hours',
                    'label' => 'Business Hours',
                    'name' => 'contact_hours',
                    'type' => 'text',
                    'instructions' => 'Business hours displayed in CTA section',
                    'required' => 0,
                    'default_value' => 'Open Mon-Fri, 9:00-17:00',
                ],
                [
                    'key' => 'field_social_facebook',
                    'label' => 'Facebook URL',
                    'name' => 'social_facebook',
                    'type' => 'url',
                    'instructions' => 'Facebook profile link',
                    'required' => 0,
                ],
                [
                    'key' => 'field_social_instagram',
                    'label' => 'Instagram URL',
                    'name' => 'social_instagram',
                    'type' => 'url',
                    'instructions' => 'Instagram profile link',
                    'required' => 0,
                ],
                [
                    'key' => 'field_social_linkedin',
                    'label' => 'LinkedIn URL',
                    'name' => 'social_linkedin',
                    'type' => 'url',
                    'instructions' => 'LinkedIn profile link',
                    'required' => 0,
                ],
                // TAB: Hero Section
                [
                    'key' => 'tab_hero',
                    'label' => 'Hero Section',
                    'name' => 'tab_hero',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_hero_logo_fin',
                    'label' => 'Financial Logo',
                    'name' => 'hero_logo_fin',
                    'type' => 'image',
                    'instructions' => 'Easy Move Financial logo for hero section',
                    'required' => 0,
                    'return_format' => 'url',
                    'preview_size' => 'thumbnail',
                ],
                [
                    'key' => 'field_hero_logo_pro',
                    'label' => 'Protection Logo',
                    'name' => 'hero_logo_pro',
                    'type' => 'image',
                    'instructions' => 'Easy Move Protection logo for hero section',
                    'required' => 0,
                    'return_format' => 'url',
                    'preview_size' => 'thumbnail',
                ],
                [
                    'key' => 'field_hero_mortgages_menu_label',
                    'label' => 'Mortgages - Menu Label',
                    'name' => 'hero_mortgages_menu_label',
                    'type' => 'text',
                    'instructions' => 'Label for mortgages in navigation menu',
                    'required' => 0,
                    'default_value' => 'Mortgages',
                ],
                [
                    'key' => 'field_hero_mortgages_menu_href',
                    'label' => 'Mortgages - Menu Link',
                    'name' => 'hero_mortgages_menu_href',
                    'type' => 'url',
                    'instructions' => 'URL for mortgages menu item',
                    'required' => 0,
                    'default_value' => '#',
                ],
                [
                    'key' => 'field_hero_mortgages_logo_top',
                    'label' => 'Mortgages - Logo Top Text',
                    'name' => 'hero_mortgages_logo_top',
                    'type' => 'text',
                    'instructions' => 'Top line of mortgages logo text',
                    'required' => 0,
                    'default_value' => 'EASYMOVE',
                ],
                [
                    'key' => 'field_hero_mortgages_logo_bottom',
                    'label' => 'Mortgages - Logo Bottom Text',
                    'name' => 'hero_mortgages_logo_bottom',
                    'type' => 'text',
                    'instructions' => 'Bottom line of mortgages logo text',
                    'required' => 0,
                    'default_value' => 'FINANCIAL',
                ],
                [
                    'key' => 'field_hero_mortgages_eyebrow',
                    'label' => 'Mortgages - Eyebrow Text',
                    'name' => 'hero_mortgages_eyebrow',
                    'type' => 'text',
                    'instructions' => 'Small text above the main title',
                    'required' => 0,
                    'default_value' => 'MORTGAGES',
                ],
                [
                    'key' => 'field_hero_mortgages_title',
                    'label' => 'Mortgages - Main Title',
                    'name' => 'hero_mortgages_title',
                    'type' => 'textarea',
                    'instructions' => 'Main heading for mortgages panel (HTML allowed - use <br> for line breaks)',
                    'required' => 0,
                    'default_value' => 'Simple, Secure,<br>Stress-Free',
                    'rows' => 3,
                ],
                [
                    'key' => 'field_hero_mortgages_text',
                    'label' => 'Mortgages - Description Text',
                    'name' => 'hero_mortgages_text',
                    'type' => 'textarea',
                    'instructions' => 'Descriptive text for mortgages panel (HTML allowed - use <br> for line breaks)',
                    'required' => 0,
                    'default_value' => 'Buying your dream home?<br>We make it clear, personal, and easy.',
                    'rows' => 3,
                ],
                [
                    'key' => 'field_hero_mortgages_button_text',
                    'label' => 'Mortgages - Button Text',
                    'name' => 'hero_mortgages_button_text',
                    'type' => 'text',
                    'instructions' => 'Text displayed on the button',
                    'required' => 0,
                    'default_value' => 'Discover',
                ],
                [
                    'key' => 'field_hero_mortgages_button_url',
                    'label' => 'Mortgages - Button URL',
                    'name' => 'hero_mortgages_button_url',
                    'type' => 'url',
                    'instructions' => 'URL the button links to',
                    'required' => 0,
                    'default_value' => '#',
                ],
                [
                    'key' => 'field_hero_mortgages_image',
                    'label' => 'Mortgages - Background Image',
                    'name' => 'hero_mortgages_image',
                    'type' => 'image',
                    'instructions' => 'Background image for mortgages panel',
                    'required' => 0,
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                ],
                [
                    'key' => 'field_hero_insurance_menu_label',
                    'label' => 'Insurance - Menu Label',
                    'name' => 'hero_insurance_menu_label',
                    'type' => 'text',
                    'instructions' => 'Label for insurance in navigation menu',
                    'required' => 0,
                    'default_value' => 'Insurance',
                ],
                [
                    'key' => 'field_hero_insurance_menu_href',
                    'label' => 'Insurance - Menu Link',
                    'name' => 'hero_insurance_menu_href',
                    'type' => 'url',
                    'instructions' => 'URL for insurance menu item',
                    'required' => 0,
                    'default_value' => '#',
                ],
                [
                    'key' => 'field_hero_insurance_logo_top',
                    'label' => 'Insurance - Logo Top Text',
                    'name' => 'hero_insurance_logo_top',
                    'type' => 'text',
                    'instructions' => 'Top line of insurance logo text',
                    'required' => 0,
                    'default_value' => 'EASYMOVE',
                ],
                [
                    'key' => 'field_hero_insurance_logo_bottom',
                    'label' => 'Insurance - Logo Bottom Text',
                    'name' => 'hero_insurance_logo_bottom',
                    'type' => 'text',
                    'instructions' => 'Bottom line of insurance logo text',
                    'required' => 0,
                    'default_value' => 'PROTECTION',
                ],
                [
                    'key' => 'field_hero_insurance_eyebrow',
                    'label' => 'Insurance - Eyebrow Text',
                    'name' => 'hero_insurance_eyebrow',
                    'type' => 'text',
                    'instructions' => 'Small text above the main title',
                    'required' => 0,
                    'default_value' => 'INSURANCE',
                ],
                [
                    'key' => 'field_hero_insurance_title',
                    'label' => 'Insurance - Main Title',
                    'name' => 'hero_insurance_title',
                    'type' => 'textarea',
                    'instructions' => 'Main heading for insurance panel (HTML allowed - use <br> for line breaks)',
                    'required' => 0,
                    'default_value' => 'Safe and<br>Protected',
                    'rows' => 3,
                ],
                [
                    'key' => 'field_hero_insurance_text',
                    'label' => 'Insurance - Description Text',
                    'name' => 'hero_insurance_text',
                    'type' => 'textarea',
                    'instructions' => 'Descriptive text for insurance panel (HTML allowed - use <br> for line breaks)',
                    'required' => 0,
                    'default_value' => 'Protecting your home or family?<br>We make it clear, personal, and easy.',
                    'rows' => 3,
                ],
                [
                    'key' => 'field_hero_insurance_button_text',
                    'label' => 'Insurance - Button Text',
                    'name' => 'hero_insurance_button_text',
                    'type' => 'text',
                    'instructions' => 'Text displayed on the button',
                    'required' => 0,
                    'default_value' => 'Discover',
                ],
                [
                    'key' => 'field_hero_insurance_button_url',
                    'label' => 'Insurance - Button URL',
                    'name' => 'hero_insurance_button_url',
                    'type' => 'url',
                    'instructions' => 'URL the button links to',
                    'required' => 0,
                    'default_value' => '#',
                ],
                [
                    'key' => 'field_hero_insurance_image',
                    'label' => 'Insurance - Background Image',
                    'name' => 'hero_insurance_image',
                    'type' => 'image',
                    'instructions' => 'Background image for insurance panel',
                    'required' => 0,
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                ],
                // TAB: Confused Section
                [
                    'key' => 'tab_confused',
                    'label' => 'Confused Section',
                    'name' => 'tab_confused',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_confused_heading',
                    'label' => 'Section Heading',
                    'name' => 'confused_heading',
                    'type' => 'textarea',
                    'instructions' => 'Main heading for the confused section (HTML allowed - use <br> for line breaks)',
                    'required' => 0,
                    'default_value' => 'Confused by mortgages?<br />Unsure about insurance?',
                    'rows' => 3,
                ],
                [
                    'key' => 'field_confused_bullets',
                    'label' => 'Bullet Points',
                    'name' => 'confused_bullets',
                    'type' => 'repeater',
                    'instructions' => 'Add the three key bullet points',
                    'required' => 0,
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'block',
                    'button_label' => 'Add Bullet',
                    'sub_fields' => [
                        [
                            'key' => 'field_confused_bullet_text',
                            'label' => 'Bullet Text',
                            'name' => 'text',
                            'type' => 'textarea',
                            'required' => 0,
                            'rows' => 2,
                        ],
                    ],
                ],
                [
                    'key' => 'field_confused_text',
                    'label' => 'Description Text',
                    'name' => 'confused_text',
                    'type' => 'wysiwyg',
                    'instructions' => 'Full description text for this section',
                    'required' => 0,
                    'default_value' => 'At Easy Move Mortgages, we cut through the confusion. Whether it\'s securing your first home, remortgaging, or protecting your loved ones, our mission is to give you <strong>clarity, confidence, and complete peace of mind.</strong>',
                    'toolbar' => 'basic',
                ],
                // TAB: Why Choose Us
                [
                    'key' => 'tab_why_choose',
                    'label' => 'Why Choose Us',
                    'name' => 'tab_why_choose',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_why_choose_heading',
                    'label' => 'Section Heading',
                    'name' => 'why_choose_heading',
                    'type' => 'text',
                    'instructions' => 'Main heading for why choose us section',
                    'required' => 0,
                    'default_value' => 'Why choose us?',
                ],
                [
                    'key' => 'field_why_choose_features',
                    'label' => 'Features',
                    'name' => 'why_choose_features',
                    'type' => 'repeater',
                    'instructions' => 'Add the three key features/benefits',
                    'required' => 0,
                    'min' => 0,
                    'max' => 3,
                    'layout' => 'block',
                    'button_label' => 'Add Feature',
                    'sub_fields' => [
                        [
                            'key' => 'field_feature_title',
                            'label' => 'Title',
                            'name' => 'title',
                            'type' => 'text',
                            'required' => 0,
                        ],
                        [
                            'key' => 'field_feature_description',
                            'label' => 'Description',
                            'name' => 'description',
                            'type' => 'textarea',
                            'required' => 0,
                            'rows' => 2,
                        ],
                    ],
                ],
                // TAB: Protect Together
                [
                    'key' => 'tab_protect',
                    'label' => 'Protect Together Section',
                    'name' => 'tab_protect',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_protect_heading',
                    'label' => 'Section Heading',
                    'name' => 'protect_heading',
                    'type' => 'textarea',
                    'instructions' => 'Main heading for protect together section (HTML allowed - use <br> for line breaks)',
                    'required' => 0,
                    'default_value' => 'Your home. Your family. Your future.<br />Let\'s protect it together.',
                    'rows' => 3,
                ],
                [
                    'key' => 'field_protect_description',
                    'label' => 'Description',
                    'name' => 'protect_description',
                    'type' => 'text',
                    'instructions' => 'Additional description text',
                    'required' => 0,
                ],
                [
                    'key' => 'field_protect_mortgage_url',
                    'label' => 'Mortgage Button URL',
                    'name' => 'protect_mortgage_url',
                    'type' => 'url',
                    'instructions' => 'URL for the Mortgage button',
                    'required' => 0,
                    'default_value' => '#',
                ],
                [
                    'key' => 'field_protect_insurance_url',
                    'label' => 'Insurance Button URL',
                    'name' => 'protect_insurance_url',
                    'type' => 'url',
                    'instructions' => 'URL for the Insurance button',
                    'required' => 0,
                    'default_value' => '#',
                ],
                // TAB: Statistics
                [
                    'key' => 'tab_statistics',
                    'label' => 'Statistics Section',
                    'name' => 'tab_statistics',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_statistics',
                    'label' => 'Statistics',
                    'name' => 'statistics',
                    'type' => 'repeater',
                    'instructions' => 'Add the four key statistics showing company achievements',
                    'required' => 0,
                    'min' => 0,
                    'max' => 4,
                    'layout' => 'block',
                    'button_label' => 'Add Statistic',
                    'sub_fields' => [
                        [
                            'key' => 'field_statistic_number',
                            'label' => 'Number/Value',
                            'name' => 'number',
                            'type' => 'text',
                            'required' => 0,
                        ],
                        [
                            'key' => 'field_statistic_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'textarea',
                            'required' => 0,
                            'rows' => 2,
                        ],
                    ],
                ],
                // TAB: Reviews
                [
                    'key' => 'tab_reviews',
                    'label' => 'Reviews Section',
                    'name' => 'tab_reviews',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_reviews_heading',
                    'label' => 'Reviews Section Heading',
                    'name' => 'reviews_heading',
                    'type' => 'text',
                    'instructions' => 'Heading for the customer reviews section',
                    'required' => 0,
                    'default_value' => 'What our customers are saying…',
                ],
                [
                    'key' => 'field_reviews_shortcode',
                    'label' => 'Reviews Plugin Shortcode',
                    'name' => 'reviews_shortcode',
                    'type' => 'text',
                    'instructions' => 'Shortcode for your reviews plugin (e.g., [your_reviews_plugin_shortcode_here])',
                    'required' => 0,
                    'default_value' => '[your_reviews_plugin_shortcode_here]',
                ],
                // TAB: Blog
                [
                    'key' => 'tab_blog',
                    'label' => 'Blog Section',
                    'name' => 'tab_blog',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 1,
                ],
                [
                    'key' => 'field_blog_heading',
                    'label' => 'Blog Section Heading',
                    'name' => 'blog_heading',
                    'type' => 'text',
                    'instructions' => 'Heading for the blog section',
                    'required' => 0,
                    'default_value' => 'Blog & Articles',
                ],
                [
                    'key' => 'field_blog_posts_count',
                    'label' => 'Number of Blog Posts to Display',
                    'name' => 'blog_posts_count',
                    'type' => 'number',
                    'instructions' => 'How many posts to display',
                    'required' => 0,
                    'default_value' => 3,
                    'min' => 1,
                    'max' => 12,
                ],
            ],
        ]);

        // About Page Field Group
        acf_add_local_field_group([
            'key' => 'group_about_page',
            'title' => 'About Page',
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'about-template.blade.php',
                    ],
                ],
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'about-template',
                    ],
                ],
            ],
            'menu_order' => 2,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'fields' => [
                // TAB: Page Title
                [
                    'key' => 'tab_about_title',
                    'label' => 'Page Title',
                    'name' => 'tab_about_title',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_page_title',
                    'label' => 'Page Title',
                    'name' => 'about_page_title',
                    'type' => 'text',
                    'instructions' => 'Main page title',
                    'required' => 0,
                    'default_value' => 'About us',
                ],
                // TAB: Why Us Section
                [
                    'key' => 'tab_about_why_us',
                    'label' => 'Why Us Section',
                    'name' => 'tab_about_why_us',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_why_us_heading',
                    'label' => 'Section Heading',
                    'name' => 'about_why_us_heading',
                    'type' => 'text',
                    'instructions' => 'Heading for the "Why us?" section',
                    'required' => 0,
                    'default_value' => 'Why us?',
                ],
                [
                    'key' => 'field_about_why_us_text',
                    'label' => 'Description Text',
                    'name' => 'about_why_us_text',
                    'type' => 'wysiwyg',
                    'instructions' => 'Full description for why us section',
                    'required' => 0,
                    'default_value' => 'We are passionate and experienced financial advisors dedicated to helping individuals and families achieve their financial goals through strategic mortgage and planning. By using our services, you gain access to personalised advice and a wide range of mortgage options. Choosing our services ensures that your dreams of owning a home will be fulfilled by trusted professionals.',
                    'toolbar' => 'basic',
                ],
                // TAB: How We Can Help Section
                [
                    'key' => 'tab_about_help',
                    'label' => 'How We Help Section',
                    'name' => 'tab_about_help',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_help_heading',
                    'label' => 'Section Heading',
                    'name' => 'about_help_heading',
                    'type' => 'text',
                    'instructions' => 'Heading for the "How can we help?" section',
                    'required' => 0,
                    'default_value' => 'How can we help?',
                ],
                [
                    'key' => 'field_about_help_text',
                    'label' => 'Description Text',
                    'name' => 'about_help_text',
                    'type' => 'wysiwyg',
                    'instructions' => 'Full description for how we help section',
                    'required' => 0,
                    'default_value' => 'We understand that navigating the path to homeownership can be overwhelming. Whether you\'re a first-time buyer or looking to refinance, our team of experts is here to guide you every step of the way. Need a free, personalised consultation? We\'re happy to answer any of your questions.',
                    'toolbar' => 'basic',
                ],
                // TAB: Our Mission Section
                [
                    'key' => 'tab_about_mission',
                    'label' => 'Our Mission Section',
                    'name' => 'tab_about_mission',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_mission_heading',
                    'label' => 'Section Heading',
                    'name' => 'about_mission_heading',
                    'type' => 'text',
                    'instructions' => 'Heading for the "Our mission" section',
                    'required' => 0,
                    'default_value' => 'Our mission',
                ],
                [
                    'key' => 'field_about_mission_highlight',
                    'label' => 'Highlighted Statement',
                    'name' => 'about_mission_highlight',
                    'type' => 'textarea',
                    'instructions' => 'Bold/highlighted mission statement',
                    'required' => 0,
                    'default_value' => 'Provide exceptional mortgage solutions tailored to each client\'s unique needs, ensuring a seamless and empowering experience on their journey to homeownership',
                    'rows' => 3,
                ],
                [
                    'key' => 'field_about_mission_text',
                    'label' => 'Full Description',
                    'name' => 'about_mission_text',
                    'type' => 'wysiwyg',
                    'instructions' => 'Full mission statement description',
                    'required' => 0,
                    'default_value' => 'Empowering individuals and families to achieve their dreams of homeownership is at the heart of our mission. By offering personalised mortgage solutions tailored to your specific needs and goals, we strive to provide a seamless and rewarding experience. With a commitment to transparency, expertise and unwavering support, we aim to guide you through every step of the process, ensuring your journey to owning a home is as smooth and successful as possible.',
                    'toolbar' => 'basic',
                ],
                // TAB: Why Choose Us
                [
                    'key' => 'tab_about_why_choose',
                    'label' => 'Why Choose Us',
                    'name' => 'tab_about_why_choose',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_why_choose_heading',
                    'label' => 'Section Heading',
                    'name' => 'about_why_choose_heading',
                    'type' => 'text',
                    'instructions' => 'Main heading for why choose us section',
                    'required' => 0,
                    'default_value' => 'Why choose us?',
                ],
                [
                    'key' => 'field_about_why_choose_features',
                    'label' => 'Features',
                    'name' => 'about_why_choose_features',
                    'type' => 'repeater',
                    'instructions' => 'Add the three key features/benefits',
                    'required' => 0,
                    'min' => 0,
                    'max' => 3,
                    'layout' => 'block',
                    'button_label' => 'Add Feature',
                    'sub_fields' => [
                        [
                            'key' => 'field_about_feature_title',
                            'label' => 'Title',
                            'name' => 'title',
                            'type' => 'text',
                            'required' => 0,
                        ],
                        [
                            'key' => 'field_about_feature_description',
                            'label' => 'Description',
                            'name' => 'description',
                            'type' => 'textarea',
                            'required' => 0,
                            'rows' => 2,
                        ],
                    ],
                ],
                // TAB: Contact & Statistics
                [
                    'key' => 'tab_about_contact',
                    'label' => 'Contact & Stats',
                    'name' => 'tab_about_contact',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_contact_phone',
                    'label' => 'Phone Number',
                    'name' => 'about_contact_phone',
                    'type' => 'text',
                    'instructions' => 'Phone number displayed in contact CTA',
                    'required' => 0,
                    'default_value' => '07555 641 081',
                ],
                [
                    'key' => 'field_about_contact_hours',
                    'label' => 'Business Hours',
                    'name' => 'about_contact_hours',
                    'type' => 'text',
                    'instructions' => 'Business hours displayed in contact CTA',
                    'required' => 0,
                    'default_value' => 'Open Mon-Fri, 9:00-17:00',
                ],
                [
                    'key' => 'field_about_statistics',
                    'label' => 'Statistics',
                    'name' => 'about_statistics',
                    'type' => 'repeater',
                    'instructions' => 'Add the four key statistics showing company achievements',
                    'required' => 0,
                    'min' => 0,
                    'max' => 4,
                    'layout' => 'block',
                    'button_label' => 'Add Statistic',
                    'sub_fields' => [
                        [
                            'key' => 'field_about_statistic_number',
                            'label' => 'Number/Value',
                            'name' => 'number',
                            'type' => 'text',
                            'required' => 0,
                        ],
                        [
                            'key' => 'field_about_statistic_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'textarea',
                            'required' => 0,
                            'rows' => 2,
                        ],
                    ],
                ],
                // TAB: Testimonials
                [
                    'key' => 'tab_about_testimonials',
                    'label' => 'Testimonials Section',
                    'name' => 'tab_about_testimonials',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 1,
                ],
                [
                    'key' => 'field_about_testimonials_heading',
                    'label' => 'Testimonials Heading',
                    'name' => 'about_testimonials_heading',
                    'type' => 'text',
                    'instructions' => 'Heading for the testimonials/reviews section',
                    'required' => 0,
                    'default_value' => 'What our customers are saying…',
                ],
                [
                    'key' => 'field_about_testimonials_shortcode',
                    'label' => 'Testimonials Plugin Shortcode',
                    'name' => 'about_testimonials_shortcode',
                    'type' => 'text',
                    'instructions' => 'Shortcode for your testimonials/reviews plugin',
                    'required' => 0,
                    'default_value' => '[your-testimonials-plugin-shortcode]',
                ],
            ],
        ]);

        acf_add_local_field_group([
            'key' => 'group_service_list',
            'title' => 'Service List Template',
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'service-list-template.blade.php',
                    ],
                ],
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'service-list-template',
                    ],
                ],
            ],
            'menu_order' => 2,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => [],
            'active' => true,
            'description' => '',
            'show_in_rest' => false,
            'fields' => [
                // TAB: Service Items
                [
                    'key' => 'tab_service_items',
                    'label' => 'Service Items',
                    'name' => 'tab_service_items',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_service_items',
                    'label' => 'Service Items',
                    'name' => 'service_items',
                    'type' => 'repeater',
                    'instructions' => 'Add mortgage or service types with descriptions and links',
                    'required' => 0,
                    'max' => '',
                    'min' => 0,
                    'layout' => 'block',
                    'button_label' => 'Add Service Item',
                    'collapsed' => '',
                    'rows' => false,
                    'sub_fields' => [
                        [
                            'key' => 'field_service_item_title',
                            'label' => 'Service Title',
                            'name' => 'title',
                            'type' => 'text',
                            'required' => 0,
                        ],
                        [
                            'key' => 'field_service_item_text',
                            'label' => 'Service Description',
                            'name' => 'text',
                            'type' => 'textarea',
                            'required' => 0,
                            'rows' => 4,
                        ],
                        [
                            'key' => 'field_service_item_image',
                            'label' => 'Service Image',
                            'name' => 'image',
                            'type' => 'image',
                            'required' => 0,
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                        ],
                        [
                            'key' => 'field_service_item_button',
                            'label' => 'Button',
                            'name' => 'button',
                            'type' => 'group',
                            'layout' => 'block',
                            'sub_fields' => [
                                [
                                    'key' => 'field_service_item_button_title',
                                    'label' => 'Button Text',
                                    'name' => 'title',
                                    'type' => 'text',
                                    'required' => 0,
                                    'default_value' => 'Read More',
                                ],
                                [
                                    'key' => 'field_service_item_button_url',
                                    'label' => 'Button URL',
                                    'name' => 'url',
                                    'type' => 'text',
                                    'required' => 0,
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ]);

        acf_add_local_field_group([
            'key' => 'group_service',
            'title' => 'Service Template',
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'service-template.blade.php',
                    ],
                ],
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'service-template',
                    ],
                ],
            ],
            'menu_order' => 3,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => [],
            'active' => true,
            'description' => '',
            'show_in_rest' => false,
            'fields' => [
                // TAB: Intro Section
                [
                    'key' => 'tab_service_intro',
                    'label' => 'Intro Section',
                    'name' => 'tab_service_intro',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_service_intro_left',
                    'label' => 'Intro Left',
                    'name' => 'intro_left',
                    'type' => 'textarea',
                    'instructions' => 'Left column intro text (shows on desktop)',
                    'required' => 0,
                    'rows' => 6,
                ],
                [
                    'key' => 'field_service_intro_right',
                    'label' => 'Intro Right',
                    'name' => 'intro_right',
                    'type' => 'textarea',
                    'instructions' => 'Right column intro text (shows on desktop)',
                    'required' => 0,
                    'rows' => 6,
                ],
                // TAB: Hero Section
                [
                    'key' => 'tab_service_hero',
                    'label' => 'Hero Section',
                    'name' => 'tab_service_hero',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_service_highlight',
                    'label' => 'Highlight Text',
                    'name' => 'highlight_text',
                    'type' => 'textarea',
                    'instructions' => 'Prominent highlight text above hero image',
                    'required' => 0,
                    'rows' => 3,
                    'default_value' => 'LET US PAVE THE PATH TO YOUR DREAM HOME WITH CLARITY, CONFIDENCE AND PEACE OF MIND!',
                ],
                [
                    'key' => 'field_service_hero_image',
                    'label' => 'Hero Image',
                    'name' => 'hero_image',
                    'type' => 'image',
                    'instructions' => 'Main service hero image. Falls back to featured image if not set.',
                    'required' => 0,
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
                // TAB: Related Services
                [
                    'key' => 'tab_service_related',
                    'label' => 'Related Services',
                    'name' => 'tab_service_related',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_service_related_services',
                    'label' => 'Related Services',
                    'name' => 'related_services',
                    'type' => 'repeater',
                    'instructions' => 'Related or alternative mortgage services to display',
                    'required' => 0,
                    'max' => '',
                    'min' => 0,
                    'layout' => 'block',
                    'button_label' => 'Add Related Service',
                    'collapsed' => '',
                    'rows' => false,
                    'sub_fields' => [
                        [
                            'key' => 'field_service_related_title',
                            'label' => 'Service Title',
                            'name' => 'title',
                            'type' => 'text',
                            'required' => 0,
                        ],
                        [
                            'key' => 'field_service_related_url',
                            'label' => 'Service URL',
                            'name' => 'url',
                            'type' => 'text',
                            'required' => 0,
                        ],
                        [
                            'key' => 'field_service_related_image',
                            'label' => 'Service Image',
                            'name' => 'image',
                            'type' => 'image',
                            'required' => 0,
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                        ],
                        [
                            'key' => 'field_service_related_button_text',
                            'label' => 'Button Text',
                            'name' => 'button_text',
                            'type' => 'text',
                            'required' => 0,
                            'default_value' => 'Read More',
                        ],
                    ],
                ],
                // TAB: CTA Section
                [
                    'key' => 'tab_service_cta',
                    'label' => 'CTA Section',
                    'name' => 'tab_service_cta',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 1,
                ],
                [
                    'key' => 'field_service_cta_heading',
                    'label' => 'CTA Heading',
                    'name' => 'cta_heading',
                    'type' => 'textarea',
                    'instructions' => 'Main heading for call-to-action section (supports HTML like <br />)',
                    'required' => 0,
                    'rows' => 3,
                    'default_value' => 'Your home. Your family. Your future.<br />Let\'s protect it together.',
                ],
                [
                    'key' => 'field_service_cta_mortgage_url',
                    'label' => 'Mortgage Button URL',
                    'name' => 'cta_mortgage_url',
                    'type' => 'text',
                    'required' => 0,
                ],
                [
                    'key' => 'field_service_cta_mortgage_text',
                    'label' => 'Mortgage Button Text',
                    'name' => 'cta_mortgage_text',
                    'type' => 'text',
                    'required' => 0,
                    'default_value' => 'Mortgage',
                ],
                [
                    'key' => 'field_service_cta_insurance_url',
                    'label' => 'Insurance Button URL',
                    'name' => 'cta_insurance_url',
                    'type' => 'text',
                    'required' => 0,
                ],
                [
                    'key' => 'field_service_cta_insurance_text',
                    'label' => 'Insurance Button Text',
                    'name' => 'cta_insurance_text',
                    'type' => 'text',
                    'required' => 0,
                    'default_value' => 'Insurance',
                ],
            ],
        ]);
    }
}
