<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AcfFieldsServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        if (! function_exists('acf_add_local_field_group')) {
            return;
        }

        add_action('acf/init', [$this, 'registerFieldGroups']);
    }

    /**
     * Register all ACF field groups for the front page.
     */
    public function registerFieldGroups(): void
    {
        $this->registerOptionsPages();

        $this->registerHeaderFooterOptionsGroup();

        acf_add_local_field_group([
            'key' => 'group_front_page',
            'title' => 'Front Page',
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'front-page.blade.php',
                    ],
                ],
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'front-page',
                    ],
                ],
            ],
            'menu_order' => 1,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'fields' => [
                // TAB: Contact Information
                [
                    'key' => 'tab_contact',
                    'label' => 'Contact Information',
                    'name' => 'tab_contact',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_contact_phone',
                    'label' => 'Phone Number',
                    'name' => 'contact_phone',
                    'type' => 'text',
                    'instructions' => 'Phone number displayed in header and contact sections',
                    'required' => 0,
                    'default_value' => '07555 641 081',
                ],
                [
                    'key' => 'field_contact_email',
                    'label' => 'Email Address',
                    'name' => 'contact_email',
                    'type' => 'email',
                    'instructions' => 'Email address displayed in header',
                    'required' => 0,
                    'default_value' => 'tomasz@emove-fs.co.uk',
                ],
                [
                    'key' => 'field_contact_social_links',
                    'label' => 'Social Links',
                    'name' => 'contact_social_links',
                    'type' => 'repeater',
                    'instructions' => 'Add social links shown in the top bar.',
                    'required' => 0,
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'block',
                    'button_label' => 'Add Social Link',
                    'sub_fields' => [
                        [
                            'key' => 'field_contact_social_link_url',
                            'label' => 'URL',
                            'name' => 'url',
                            'type' => 'url',
                            'required' => 1,
                        ],
                        [
                            'key' => 'field_contact_social_link_icon_class',
                            'label' => 'Icon Class',
                            'name' => 'icon_class',
                            'type' => 'font-awesome',
                        ],
                    ],
                ],
                // TAB: Hero Section
                [
                    'key' => 'tab_hero',
                    'label' => 'Hero Section',
                    'name' => 'tab_hero',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_hero_logo_fin',
                    'label' => 'Financial Logo',
                    'name' => 'hero_logo_fin',
                    'type' => 'image',
                    'instructions' => 'Easy Move Financial logo for hero section',
                    'required' => 0,
                    'return_format' => 'url',
                    'preview_size' => 'thumbnail',
                ],
                [
                    'key' => 'field_hero_logo_pro',
                    'label' => 'Protection Logo',
                    'name' => 'hero_logo_pro',
                    'type' => 'image',
                    'instructions' => 'Easy Move Protection logo for hero section',
                    'required' => 0,
                    'return_format' => 'url',
                    'preview_size' => 'thumbnail',
                ],
                [
                    'key' => 'field_hero_mortgages_eyebrow',
                    'label' => 'Mortgages - Eyebrow Text',
                    'name' => 'hero_mortgages_eyebrow',
                    'type' => 'text',
                    'instructions' => 'Small text above the main title',
                    'required' => 0,
                    'default_value' => 'MORTGAGES',
                ],
                [
                    'key' => 'field_hero_mortgages_title',
                    'label' => 'Mortgages - Main Title',
                    'name' => 'hero_mortgages_title',
                    'type' => 'textarea',
                    'instructions' => 'Main heading for mortgages panel (HTML allowed - use <br> for line breaks)',
                    'required' => 0,
                    'default_value' => 'Simple, Secure,<br>Stress-Free',
                    'rows' => 3,
                ],
                [
                    'key' => 'field_hero_mortgages_text',
                    'label' => 'Mortgages - Description Text',
                    'name' => 'hero_mortgages_text',
                    'type' => 'textarea',
                    'instructions' => 'Descriptive text for mortgages panel (HTML allowed - use <br> for line breaks)',
                    'required' => 0,
                    'default_value' => 'Buying your dream home?<br>We make it clear, personal, and easy.',
                    'rows' => 3,
                ],
                [
                    'key' => 'field_hero_mortgages_button_text',
                    'label' => 'Mortgages - Button Text',
                    'name' => 'hero_mortgages_button_text',
                    'type' => 'text',
                    'instructions' => 'Text displayed on the button',
                    'required' => 0,
                    'default_value' => 'Discover',
                ],
                [
                    'key' => 'field_hero_mortgages_button_url',
                    'label' => 'Mortgages - Button URL',
                    'name' => 'hero_mortgages_button_url',
                    'type' => 'url',
                    'instructions' => 'URL the button links to',
                    'required' => 0,
                    'default_value' => '#',
                ],
                [
                    'key' => 'field_hero_mortgages_video',
                    'label' => 'Mortgages - Background Video',
                    'name' => 'hero_mortgages_video',
                    'type' => 'file',
                    'required' => 0,
                    'return_format' => 'url',
                    'mime_types' => 'mp4,mov,webm,ogg',
                ],
                [
                    'key' => 'field_hero_insurance_eyebrow',
                    'label' => 'Insurance - Eyebrow Text',
                    'name' => 'hero_insurance_eyebrow',
                    'type' => 'text',
                    'instructions' => 'Small text above the main title',
                    'required' => 0,
                    'default_value' => 'INSURANCE',
                ],
                [
                    'key' => 'field_hero_insurance_title',
                    'label' => 'Insurance - Main Title',
                    'name' => 'hero_insurance_title',
                    'type' => 'textarea',
                    'instructions' => 'Main heading for insurance panel (HTML allowed - use <br> for line breaks)',
                    'required' => 0,
                    'default_value' => 'Safe and<br>Protected',
                    'rows' => 3,
                ],
                [
                    'key' => 'field_hero_insurance_text',
                    'label' => 'Insurance - Description Text',
                    'name' => 'hero_insurance_text',
                    'type' => 'textarea',
                    'instructions' => 'Descriptive text for insurance panel (HTML allowed - use <br> for line breaks)',
                    'required' => 0,
                    'default_value' => 'Protecting your home or family?<br>We make it clear, personal, and easy.',
                    'rows' => 3,
                ],
                [
                    'key' => 'field_hero_insurance_button_text',
                    'label' => 'Insurance - Button Text',
                    'name' => 'hero_insurance_button_text',
                    'type' => 'text',
                    'instructions' => 'Text displayed on the button',
                    'required' => 0,
                    'default_value' => 'Discover',
                ],
                [
                    'key' => 'field_hero_insurance_button_url',
                    'label' => 'Insurance - Button URL',
                    'name' => 'hero_insurance_button_url',
                    'type' => 'url',
                    'instructions' => 'URL the button links to',
                    'required' => 0,
                    'default_value' => '#',
                ],
                [
                    'key' => 'field_hero_insurance_video',
                    'label' => 'Insurance - Background Video',
                    'name' => 'hero_insurance_video',
                    'type' => 'file',
                    'required' => 0,
                    'return_format' => 'url',
                    'mime_types' => 'mp4,mov,webm,ogg',
                ],
                // TAB: Confused Section
                [
                    'key' => 'tab_confused',
                    'label' => 'Confused Section',
                    'name' => 'tab_confused',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_confused_heading',
                    'label' => 'Section Heading',
                    'name' => 'confused_heading',
                    'type' => 'textarea',
                    'instructions' => 'Main heading for the confused section (HTML allowed - use <br> for line breaks)',
                    'required' => 0,
                    'default_value' => 'Confused by mortgages?<br />Unsure about insurance?',
                    'rows' => 3,
                ],
                [
                    'key' => 'field_confused_bullets',
                    'label' => 'Bullet Points',
                    'name' => 'confused_bullets',
                    'type' => 'repeater',
                    'instructions' => 'Add the three key bullet points',
                    'required' => 0,
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'block',
                    'button_label' => 'Add Bullet',
                    'sub_fields' => [
                        [
                            'key' => 'field_confused_bullet_text',
                            'label' => 'Bullet Text',
                            'name' => 'text',
                            'type' => 'textarea',
                            'required' => 0,
                            'rows' => 2,
                        ],
                    ],
                ],
                [
                    'key' => 'field_confused_text',
                    'label' => 'Description Text',
                    'name' => 'confused_text',
                    'type' => 'wysiwyg',
                    'instructions' => 'Full description text for this section',
                    'required' => 0,
                    'default_value' => 'At Easy Move Mortgages, we cut through the confusion. Whether it\'s securing your first home, remortgaging, or protecting your loved ones, our mission is to give you <strong>clarity, confidence, and complete peace of mind.</strong>',
                    'toolbar' => 'basic',
                ],
                // TAB: Why Choose Us
                [
                    'key' => 'tab_why_choose',
                    'label' => 'Why Choose Us',
                    'name' => 'tab_why_choose',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_why_choose_heading',
                    'label' => 'Section Heading',
                    'name' => 'why_choose_heading',
                    'type' => 'text',
                    'instructions' => 'Main heading for why choose us section',
                    'required' => 0,
                    'default_value' => 'Why choose us?',
                ],
                [
                    'key' => 'field_why_choose_image',
                    'label' => 'Section Image',
                    'name' => 'why_choose_image',
                    'type' => 'image',
                    'instructions' => 'Top image displayed in the Why choose us section',
                    'required' => 0,
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                ],
                [
                    'key' => 'field_why_choose_features',
                    'label' => 'Features',
                    'name' => 'why_choose_features',
                    'type' => 'repeater',
                    'instructions' => 'Add the three key features/benefits',
                    'required' => 0,
                    'min' => 0,
                    'max' => 3,
                    'layout' => 'block',
                    'button_label' => 'Add Feature',
                    'sub_fields' => [
                        [
                            'key' => 'field_feature_title',
                            'label' => 'Title',
                            'name' => 'title',
                            'type' => 'text',
                            'required' => 0,
                        ],
                        [
                            'key' => 'field_feature_description',
                            'label' => 'Description',
                            'name' => 'description',
                            'type' => 'textarea',
                            'required' => 0,
                            'rows' => 2,
                        ],
                        [
                            'key' => 'field_feature_icon',
                            'label' => 'Icon',
                            'name' => 'icon',
                            'type' => 'image',
                            'required' => 0,
                            'return_format' => 'url',
                            'preview_size' => 'thumbnail',
                        ],
                    ],
                ],

                [
                    'key' => 'field_contact_hours',
                    'label' => 'Business Hours',
                    'name' => 'contact_hours',
                    'type' => 'text',
                    'instructions' => 'Business hours displayed in CTA section',
                    'required' => 0,
                    'default_value' => 'Open Mon-Fri, 9:00-17:00',
                ],
                [
                    'key' => 'field_contact_heading',
                    'label' => 'Contact CTA Heading',
                    'name' => 'contact_heading',
                    'type' => 'text',
                    'instructions' => 'Heading displayed in the yellow contact strip',
                    'required' => 0,
                    'default_value' => 'Get in touch',
                ],
                [
                    'key' => 'field_reviews_heading',
                    'label' => 'Reviews Section Heading',
                    'name' => 'reviews_heading',
                    'type' => 'text',
                    'instructions' => 'Heading for the customer reviews section',
                    'required' => 0,
                    'default_value' => 'What our customers are saying…',
                ],
                [
                    'key' => 'field_reviews_shortcode',
                    'label' => 'Reviews Plugin Shortcode',
                    'name' => 'reviews_shortcode',
                    'type' => 'text',
                    'instructions' => 'Shortcode for your reviews plugin (e.g., [your_reviews_plugin_shortcode_here])',
                    'required' => 0,
                    'default_value' => '[trustindex no-registration=google]',
                ],
                // TAB: Protect Together
                [
                    'key' => 'tab_protect',
                    'label' => 'Protect Together Section',
                    'name' => 'tab_protect',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_protect_heading',
                    'label' => 'Section Heading',
                    'name' => 'protect_heading',
                    'type' => 'textarea',
                    'instructions' => 'Main heading for protect together section (HTML allowed - use <br> for line breaks)',
                    'required' => 0,
                    'default_value' => 'Your home. Your family. Your future.<br />Let\'s protect it together.',
                    'rows' => 3,
                ],
                [
                    'key' => 'field_protect_description',
                    'label' => 'Description',
                    'name' => 'protect_description',
                    'type' => 'text',
                    'instructions' => 'Additional description text',
                    'required' => 0,
                ],
                [
                    'key' => 'field_protect_video',
                    'label' => 'Background Video',
                    'name' => 'protect_video',
                    'type' => 'file',
                    'instructions' => 'Background video used in the Protect Together section',
                    'required' => 0,
                    'return_format' => 'url',
                    'mime_types' => 'mp4,mov,webm,ogg',
                ],
                [
                    'key' => 'field_protect_video_poster',
                    'label' => 'Video Poster Image',
                    'name' => 'protect_video_poster',
                    'type' => 'image',
                    'instructions' => 'Poster image shown before the background video loads',
                    'required' => 0,
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                ],
                [
                    'key' => 'field_protect_mortgage_url',
                    'label' => 'Mortgage Button URL',
                    'name' => 'protect_mortgage_url',
                    'type' => 'url',
                    'instructions' => 'URL for the Mortgage button',
                    'required' => 0,
                    'default_value' => '#',
                ],
                [
                    'key' => 'field_protect_mortgage_text',
                    'label' => 'Mortgage Button Text',
                    'name' => 'protect_mortgage_text',
                    'type' => 'text',
                    'instructions' => 'Label for the Mortgage CTA button',
                    'required' => 0,
                    'default_value' => 'Mortgage',
                ],
                [
                    'key' => 'field_protect_insurance_url',
                    'label' => 'Insurance Button URL',
                    'name' => 'protect_insurance_url',
                    'type' => 'url',
                    'instructions' => 'URL for the Insurance button',
                    'required' => 0,
                    'default_value' => '#',
                ],
                [
                    'key' => 'field_protect_insurance_text',
                    'label' => 'Insurance Button Text',
                    'name' => 'protect_insurance_text',
                    'type' => 'text',
                    'instructions' => 'Label for the Insurance CTA button',
                    'required' => 0,
                    'default_value' => 'Insurance',
                ],
                // TAB: Statistics
                [
                    'key' => 'tab_statistics',
                    'label' => 'Statistics Section',
                    'name' => 'tab_statistics',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_statistics_background_image',
                    'label' => 'Background Image',
                    'name' => 'statistics_background_image',
                    'type' => 'image',
                    'instructions' => 'Background image for the statistics section.',
                    'required' => 0,
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                ],

                [
                    'key' => 'field_statistics',
                    'label' => 'Statistics',
                    'name' => 'statistics',
                    'type' => 'repeater',
                    'instructions' => 'Add the four key statistics showing company achievements',
                    'required' => 0,
                    'min' => 0,
                    'max' => 4,
                    'layout' => 'block',
                    'button_label' => 'Add Statistic',
                    'sub_fields' => [
                        [
                            'key' => 'field_statistic_number',
                            'label' => 'Number/Value',
                            'name' => 'number',
                            'type' => 'text',
                            'required' => 0,
                        ],
                        [
                            'key' => 'field_statistic_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'textarea',
                            'required' => 0,
                            'rows' => 2,
                        ],
                    ],
                ],
                // TAB: Blog
                [
                    'key' => 'tab_blog',
                    'label' => 'Blog Section',
                    'name' => 'tab_blog',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_blog_heading',
                    'label' => 'Blog Section Heading',
                    'name' => 'blog_heading',
                    'type' => 'text',
                    'instructions' => 'Heading for the blog section',
                    'required' => 0,
                    'default_value' => 'Blog & Articles',
                ],
                [
                    'key' => 'field_blog_posts_count',
                    'label' => 'Number of Blog Posts to Display',
                    'name' => 'blog_posts_count',
                    'type' => 'number',
                    'instructions' => 'How many posts to display',
                    'required' => 0,
                    'default_value' => 3,
                    'min' => 1,
                    'max' => 12,
                ],
                [
                    'key' => 'field_front_blog_read_more_text',
                    'label' => 'Front Blog Card Button Text',
                    'name' => 'front_blog_read_more_text',
                    'type' => 'text',
                    'required' => 0,
                    'default_value' => 'Read more',
                ],
                [
                    'key' => 'field_front_blog_archive_button_text',
                    'label' => 'Front Blog Archive Button Text',
                    'name' => 'front_blog_archive_button_text',
                    'type' => 'text',
                    'required' => 0,
                    'default_value' => 'See all articles',
                ],
            ],
        ]);

        // About Page Field Group
        acf_add_local_field_group([
            'key' => 'group_about_page',
            'title' => 'About Page',
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'about-template.blade.php',
                    ],
                ],
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'about-template',
                    ],
                ],
            ],
            'menu_order' => 2,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'fields' => [
                // TAB: Breadcrumbs
                [
                    'key' => 'tab_about_breadcrumbs',
                    'label' => 'Breadcrumbs',
                    'name' => 'tab_about_breadcrumbs',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_breadcrumb_items',
                    'label' => 'Breadcrumb Items',
                    'name' => 'about_breadcrumb_items',
                    'type' => 'repeater',
                    'instructions' => 'Optional items before the current page. Leave empty to use default breadcrumb.',
                    'required' => 0,
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => 'Add Breadcrumb Item',
                    'sub_fields' => [
                        [
                            'key' => 'field_about_breadcrumb_item_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                            'required' => 1,
                        ],
                        [
                            'key' => 'field_about_breadcrumb_item_url',
                            'label' => 'URL',
                            'name' => 'url',
                            'type' => 'url',
                            'required' => 0,
                        ],
                    ],
                ],
                // TAB: Page Title
                [
                    'key' => 'tab_about_title',
                    'label' => 'Page Title',
                    'name' => 'tab_about_title',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_page_title',
                    'label' => 'Page Title',
                    'name' => 'about_page_title',
                    'type' => 'text',
                    'instructions' => 'Main page title',
                    'required' => 0,
                    'default_value' => 'About us',
                ],
                [
                    'key' => 'field_about_hero_image',
                    'label' => 'Hero Image',
                    'name' => 'about_hero_image',
                    'type' => 'image',
                    'instructions' => 'Top image used in the About page dark section.',
                    'required' => 0,
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                ],
                // TAB: Our Mission Section
                [
                    'key' => 'tab_about_mission',
                    'label' => 'Our Mission Section',
                    'name' => 'tab_about_mission',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_why_us_heading',
                    'label' => 'Why us Section Heading',
                    'name' => 'about_why_us_heading',
                    'type' => 'text',
                    'instructions' => 'Heading for the "Why US?" section',
                    'required' => 0,
                    'default_value' => 'Why us?',
                ],
                [
                    'key' => 'field_about_why_us_text',
                    'label' => 'Why us Text',
                    'name' => 'about_why_us_text',
                    'type' => 'textarea',
                    'instructions' => 'Text for the "Why US?" section',
                    'required' => 0,
                    'default_value' => 'We are passionate and experienced financial advisors dedicated to helping individuals and families achieve their financial goals through strategic mortgage and planning. By using our services, you gain access to personalised advice and a wide range of mortgage options. Choosing our services ensures that your dreams of owning a home will be fulfilled by trusted professionals.',
                    'rows' => 3,
                ],
                [
                    'key' => 'field_about_help_heading',
                    'label' => 'Help Section Heading',
                    'name' => 'about_help_heading',
                    'type' => 'text',
                    'instructions' => 'Heading for the "Help" section',
                    'required' => 0,
                    'default_value' => 'How can we help?',
                ],
                [
                    'key' => 'field_about_help_text',
                    'label' => 'Help Text',
                    'name' => 'about_help_text',
                    'type' => 'textarea',
                    'instructions' => 'Text for the "Help" section',
                    'required' => 0,
                    'default_value' => "We understand that navigating the path to homeownership can be overwhelming. Whether you're a first-time buyer or looking to refinance, our team of experts is here to guide you every step of the way. Need a free, personalised consultation? We're happy to answer any of your questions.",
                    'rows' => 3,
                ],
                [
                    'key' => 'field_about_mission_heading',
                    'label' => 'Our mission Section Heading',
                    'name' => 'about_mission_heading',
                    'type' => 'text',
                    'instructions' => 'Heading for the "Our mission" section',
                    'required' => 0,
                    'default_value' => 'Our mission',
                ],
                [
                    'key' => 'field_about_mission_highlight',
                    'label' => 'Highlighted Statement',
                    'name' => 'about_mission_highlight',
                    'type' => 'textarea',
                    'instructions' => 'Bold/highlighted mission statement',
                    'required' => 0,
                    'default_value' => 'Provide exceptional mortgage solutions tailored to each client\'s unique needs, ensuring a seamless and empowering experience on their journey to homeownership',
                    'rows' => 3,
                ],
                [
                    'key' => 'field_about_mission_text',
                    'label' => 'Full Description',
                    'name' => 'about_mission_text',
                    'type' => 'wysiwyg',
                    'instructions' => 'Full mission statement description',
                    'required' => 0,
                    'default_value' => 'Empowering individuals and families to achieve their dreams of homeownership is at the heart of our mission. By offering personalised mortgage solutions tailored to your specific needs and goals, we strive to provide a seamless and rewarding experience. With a commitment to transparency, expertise and unwavering support, we aim to guide you through every step of the process, ensuring your journey to owning a home is as smooth and successful as possible.',
                    'toolbar' => 'basic',
                ],
                // TAB: Why Choose Us
                [
                    'key' => 'tab_about_why_choose',
                    'label' => 'Why Choose Us',
                    'name' => 'tab_about_why_choose',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_why_choose_heading',
                    'label' => 'Section Heading',
                    'name' => 'about_why_choose_heading',
                    'type' => 'text',
                    'instructions' => 'Main heading for why choose us section',
                    'required' => 0,
                    'default_value' => 'Why choose us?',
                ],
                [
                    'key' => 'field_about_why_choose_features',
                    'label' => 'Features',
                    'name' => 'about_why_choose_features',
                    'type' => 'repeater',
                    'instructions' => 'Add the three key features/benefits',
                    'required' => 0,
                    'min' => 0,
                    'max' => 3,
                    'layout' => 'block',
                    'button_label' => 'Add Feature',
                    'sub_fields' => [
                        [
                            'key' => 'field_about_feature_title',
                            'label' => 'Title',
                            'name' => 'title',
                            'type' => 'text',
                            'required' => 0,
                        ],
                        [
                            'key' => 'field_about_feature_description',
                            'label' => 'Description',
                            'name' => 'description',
                            'type' => 'textarea',
                            'required' => 0,
                            'rows' => 2,
                        ],
                        [
                            'key' => 'field_about_feature_icon',
                            'label' => 'Icon',
                            'name' => 'icon',
                            'type' => 'image',
                            'required' => 0,
                            'return_format' => 'url',
                            'preview_size' => 'thumbnail',
                        ],
                    ],
                ],
                [
                    'key' => 'field_about_contact_phone',
                    'label' => 'Phone Number',
                    'name' => 'about_contact_phone',
                    'type' => 'text',
                    'instructions' => 'Phone number displayed in contact CTA',
                    'required' => 0,
                    'default_value' => '07555 641 081',
                ],
                [
                    'key' => 'field_about_contact_heading',
                    'label' => 'Contact CTA Heading',
                    'name' => 'about_contact_heading',
                    'type' => 'text',
                    'instructions' => 'Heading shown above phone and opening hours',
                    'required' => 0,
                    'default_value' => 'Give us a call',
                ],
                [
                    'key' => 'field_about_contact_hours',
                    'label' => 'Business Hours',
                    'name' => 'about_contact_hours',
                    'type' => 'text',
                    'instructions' => 'Business hours displayed in contact CTA',
                    'required' => 0,
                    'default_value' => 'Open Mon-Fri, 9:00-17:00',
                ],
                // TAB: Testimonials
                [
                    'key' => 'tab_about_testimonials',
                    'label' => 'Testimonials Section',
                    'name' => 'tab_about_testimonials',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_testimonials_heading',
                    'label' => 'Testimonials Heading',
                    'name' => 'about_testimonials_heading',
                    'type' => 'text',
                    'instructions' => 'Heading for the testimonials/reviews section',
                    'required' => 0,
                    'default_value' => 'What our customers are saying…',
                ],
                [
                    'key' => 'field_about_testimonials_shortcode',
                    'label' => 'Testimonials Plugin Shortcode',
                    'name' => 'about_testimonials_shortcode',
                    'type' => 'text',
                    'instructions' => 'Shortcode for your testimonials/reviews plugin',
                    'required' => 0,
                    'default_value' => '[trustindex no-registration=google]',
                ],
                // TAB: Statistics
                [
                    'key' => 'tab_about_statistics',
                    'label' => 'Statistics Section',
                    'name' => 'tab_about_statistics',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_about_statistics_background_image',
                    'label' => 'Statistics Background Image',
                    'name' => 'about_statistics_background_image',
                    'type' => 'image',
                    'instructions' => 'Background image used behind statistics section.',
                    'required' => 0,
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                ],
                [
                    'key' => 'field_about_statistics',
                    'label' => 'Statistics',
                    'name' => 'about_statistics',
                    'type' => 'repeater',
                    'instructions' => 'Add the four key statistics showing company achievements',
                    'required' => 0,
                    'min' => 0,
                    'max' => 4,
                    'layout' => 'block',
                    'button_label' => 'Add Statistic',
                    'sub_fields' => [
                        [
                            'key' => 'field_about_statistic_number',
                            'label' => 'Number/Value',
                            'name' => 'number',
                            'type' => 'text',
                            'required' => 0,
                        ],
                        [
                            'key' => 'field_about_statistic_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'textarea',
                            'required' => 0,
                            'rows' => 2,
                        ],
                    ],
                ],
            ],
        ]);

        acf_add_local_field_group([
            'key' => 'group_service_list',
            'title' => 'Service List Template',
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'service-list-template.blade.php',
                    ],
                ],
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'service-list-template',
                    ],
                ],
            ],
            'menu_order' => 2,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => [],
            'active' => true,
            'description' => '',
            'show_in_rest' => false,
            'fields' => [
                // TAB: Breadcrumbs
                [
                    'key' => 'tab_service_list_breadcrumbs',
                    'label' => 'Breadcrumbs',
                    'name' => 'tab_service_list_breadcrumbs',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_service_list_breadcrumb_items',
                    'label' => 'Breadcrumb Items',
                    'name' => 'service_list_breadcrumb_items',
                    'type' => 'repeater',
                    'instructions' => 'Optional items before the current page. Leave empty to use default breadcrumb.',
                    'required' => 0,
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => 'Add Breadcrumb Item',
                    'sub_fields' => [
                        [
                            'key' => 'field_service_list_breadcrumb_item_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                            'required' => 1,
                        ],
                        [
                            'key' => 'field_service_list_breadcrumb_item_url',
                            'label' => 'URL',
                            'name' => 'url',
                            'type' => 'url',
                            'required' => 0,
                        ],
                    ],
                ],
                // TAB: Service Items
                [
                    'key' => 'tab_service_items',
                    'label' => 'Service Items',
                    'name' => 'tab_service_items',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_service_items',
                    'label' => 'Service Items',
                    'name' => 'service_items',
                    'type' => 'repeater',
                    'instructions' => 'Add mortgage or service types with descriptions and links',
                    'required' => 0,
                    'max' => '',
                    'min' => 0,
                    'layout' => 'block',
                    'button_label' => 'Add Service Item',
                    'collapsed' => '',
                    'rows' => false,
                    'sub_fields' => [
                        [
                            'key' => 'field_service_item_title',
                            'label' => 'Service Title',
                            'name' => 'title',
                            'type' => 'text',
                            'required' => 0,
                        ],
                        [
                            'key' => 'field_service_item_text',
                            'label' => 'Service Description',
                            'name' => 'text',
                            'type' => 'textarea',
                            'required' => 0,
                            'rows' => 4,
                        ],
                        [
                            'key' => 'field_service_item_image',
                            'label' => 'Service Image',
                            'name' => 'image',
                            'type' => 'image',
                            'required' => 0,
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                        ],
                        [
                            'key' => 'field_service_item_button',
                            'label' => 'Button',
                            'name' => 'button',
                            'type' => 'group',
                            'layout' => 'block',
                            'sub_fields' => [
                                [
                                    'key' => 'field_service_item_button_title',
                                    'label' => 'Button Text',
                                    'name' => 'title',
                                    'type' => 'text',
                                    'required' => 0,
                                    'default_value' => 'Read More',
                                ],
                                [
                                    'key' => 'field_service_item_button_url',
                                    'label' => 'Button URL',
                                    'name' => 'url',
                                    'type' => 'text',
                                    'required' => 0,
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ]);

        acf_add_local_field_group([
            'key' => 'group_service',
            'title' => 'Service Template',
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'service-template.blade.php',
                    ],
                ],
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'service-template',
                    ],
                ],
            ],
            'menu_order' => 3,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => [],
            'active' => true,
            'description' => '',
            'show_in_rest' => false,
            'fields' => [
                // TAB: Breadcrumbs
                [
                    'key' => 'tab_service_breadcrumbs',
                    'label' => 'Breadcrumbs',
                    'name' => 'tab_service_breadcrumbs',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_service_breadcrumb_items',
                    'label' => 'Breadcrumb Items',
                    'name' => 'service_breadcrumb_items',
                    'type' => 'repeater',
                    'instructions' => 'Optional items before the current page. Leave empty to use default breadcrumb.',
                    'required' => 0,
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => 'Add Breadcrumb Item',
                    'sub_fields' => [
                        [
                            'key' => 'field_service_breadcrumb_item_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                            'required' => 1,
                        ],
                        [
                            'key' => 'field_service_breadcrumb_item_url',
                            'label' => 'URL',
                            'name' => 'url',
                            'type' => 'url',
                            'required' => 0,
                        ],
                    ],
                ],
                // TAB: Intro Section
                [
                    'key' => 'tab_service_intro',
                    'label' => 'Intro Section',
                    'name' => 'tab_service_intro',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_service_page_title',
                    'label' => 'Page Title Override',
                    'name' => 'page_title',
                    'type' => 'text',
                    'instructions' => 'Optional page title override. Falls back to page title when empty.',
                    'required' => 0,
                ],
                [
                    'key' => 'field_service_intro_left',
                    'label' => 'Intro Left',
                    'name' => 'intro_left',
                    'type' => 'textarea',
                    'instructions' => 'Left column intro text (shows on desktop)',
                    'required' => 0,
                    'rows' => 6,
                ],
                [
                    'key' => 'field_service_intro_right',
                    'label' => 'Intro Right',
                    'name' => 'intro_right',
                    'type' => 'textarea',
                    'instructions' => 'Right column intro text (shows on desktop)',
                    'required' => 0,
                    'rows' => 6,
                ],
                // TAB: Hero Section
                [
                    'key' => 'tab_service_hero',
                    'label' => 'Hero Section',
                    'name' => 'tab_service_hero',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_service_highlight',
                    'label' => 'Highlight Text',
                    'name' => 'highlight_text',
                    'type' => 'textarea',
                    'instructions' => 'Prominent highlight text above hero image',
                    'required' => 0,
                    'rows' => 3,
                    'default_value' => 'LET US PAVE THE PATH TO YOUR DREAM HOME WITH CLARITY, CONFIDENCE AND PEACE OF MIND!',
                ],
                [
                    'key' => 'field_service_hero_image',
                    'label' => 'Hero Image',
                    'name' => 'hero_image',
                    'type' => 'image',
                    'instructions' => 'Main service hero image. Falls back to featured image if not set.',
                    'required' => 0,
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
                // TAB: Related Services
                [
                    'key' => 'tab_service_related',
                    'label' => 'Related Services',
                    'name' => 'tab_service_related',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_service_related_services_heading',
                    'label' => 'Related Services Heading',
                    'name' => 'related_services_heading',
                    'type' => 'text',
                    'required' => 0,
                    'default_value' => 'Related services',
                ],
                [
                    'key' => 'field_service_related_services',
                    'label' => 'Related Services',
                    'name' => 'related_services',
                    'type' => 'repeater',
                    'instructions' => 'Related or alternative mortgage services to display',
                    'required' => 0,
                    'max' => '',
                    'min' => 0,
                    'layout' => 'block',
                    'button_label' => 'Add Related Service',
                    'collapsed' => '',
                    'rows' => false,
                    'sub_fields' => [
                        [
                            'key' => 'field_service_related_title',
                            'label' => 'Service Title',
                            'name' => 'title',
                            'type' => 'text',
                            'required' => 0,
                        ],
                        [
                            'key' => 'field_service_related_url',
                            'label' => 'Service URL',
                            'name' => 'url',
                            'type' => 'text',
                            'required' => 0,
                        ],
                        [
                            'key' => 'field_service_related_image',
                            'label' => 'Service Image',
                            'name' => 'image',
                            'type' => 'image',
                            'required' => 0,
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                        ],
                        [
                            'key' => 'field_service_related_button_text',
                            'label' => 'Button Text',
                            'name' => 'button_text',
                            'type' => 'text',
                            'required' => 0,
                            'default_value' => 'Read More',
                        ],
                    ],
                ],
                // TAB: CTA Section
                [
                    'key' => 'tab_service_cta',
                    'label' => 'CTA Section',
                    'name' => 'tab_service_cta',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_service_cta_heading',
                    'label' => 'CTA Heading',
                    'name' => 'cta_heading',
                    'type' => 'textarea',
                    'instructions' => 'Main heading for call-to-action section (supports HTML like <br />)',
                    'required' => 0,
                    'rows' => 3,
                    'default_value' => 'Your home. Your family. Your future.<br />Let\'s protect it together.',
                ],
                [
                    'key' => 'field_service_cta_url',
                    'label' => 'Button URL',
                    'name' => 'cta_url',
                    'type' => 'text',
                    'required' => 0,
                ],
                [
                    'key' => 'field_service_cta_text',
                    'label' => 'Button Text',
                    'name' => 'cta_text',
                    'type' => 'text',
                    'required' => 0,
                ],
                [
                    'key' => 'field_hero_mortgages_video',
                    'label' => 'Banner Video',
                    'name' => 'hero_mortgages_video',
                    'type' => 'file',
                    'required' => 0,
                    'return_format' => 'url',
                    'mime_types' => 'mp4,mov,webm,ogg',
                ],
                [
                    'key' => 'field_hero_mortgages_video_poster',
                    'label' => 'Video Poster Image',
                    'name' => 'hero_mortgages_videoPoster',
                    'type' => 'image',
                    'required' => 0,
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                ],
            ],
        ]);

        acf_add_local_field_group([
            'key' => 'group_blog_post',
            'title' => 'Blog Post',
            'location' => [
                [
                    [
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'post',
                    ],
                ],
            ],
            'menu_order' => 4,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => [],
            'active' => true,
            'description' => '',
            'show_in_rest' => false,
            'fields' => [
                // TAB: Breadcrumbs
                [
                    'key' => 'tab_post_breadcrumbs',
                    'label' => 'Breadcrumbs',
                    'name' => 'tab_post_breadcrumbs',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_post_breadcrumb_items',
                    'label' => 'Breadcrumb Items',
                    'name' => 'post_breadcrumb_items',
                    'type' => 'repeater',
                    'instructions' => 'Optional items before the current post. Leave empty to use default breadcrumb.',
                    'required' => 0,
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => 'Add Breadcrumb Item',
                    'sub_fields' => [
                        [
                            'key' => 'field_post_breadcrumb_item_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                            'required' => 1,
                        ],
                        [
                            'key' => 'field_post_breadcrumb_item_url',
                            'label' => 'URL',
                            'name' => 'url',
                            'type' => 'url',
                            'required' => 0,
                        ],
                    ],
                ],
                [
                    'key' => 'field_post_content_wysiwyg',
                    'label' => 'Post Content',
                    'name' => 'post_content_wysiwyg',
                    'type' => 'wysiwyg',
                    'instructions' => 'Main post content. Falls back to the default WordPress editor if not set.',
                    'required' => 0,
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'default_value' => '',
                    'tabs' => 'all',
                    'delay' => 1,
                ],
                [
                    'key' => 'field_post_thumbnail_override',
                    'label' => 'Post Thumbnail Override',
                    'name' => 'post_thumbnail_override',
                    'type' => 'image',
                    'instructions' => 'Optional override image used in post listings (Front Page and Blog Template).',
                    'required' => 0,
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ],
            ],
        ]);

        acf_add_local_field_group([
            'key' => 'group_contact',
            'title' => 'Contact Template',
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'contact-template.blade.php',
                    ],
                ],
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'contact-template',
                    ],
                ],
            ],
            'menu_order' => 5,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => [],
            'active' => true,
            'description' => '',
            'show_in_rest' => false,
            'fields' => [
                // TAB: Page Settings
                [
                    'key' => 'tab_contact_settings',
                    'label' => 'Page Settings',
                    'name' => 'tab_contact_settings',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_contact_page_heading',
                    'label' => 'Page Heading',
                    'name' => 'contact_page_heading',
                    'type' => 'text',
                    'required' => 0,
                    'default_value' => 'Contact',
                ],
                [
                    'key' => 'field_contact_breadcrumb_items',
                    'label' => 'Breadcrumb Items',
                    'name' => 'contact_breadcrumb_items',
                    'type' => 'repeater',
                    'instructions' => 'Build breadcrumb trail. The current page is appended automatically as the last item.',
                    'required' => 0,
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => 'Add Breadcrumb Item',
                    'sub_fields' => [
                        [
                            'key' => 'field_contact_breadcrumb_item_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                            'required' => 1,
                        ],
                        [
                            'key' => 'field_contact_breadcrumb_item_url',
                            'label' => 'URL',
                            'name' => 'url',
                            'type' => 'url',
                            'required' => 0,
                        ],
                    ],
                ],
                // TAB: Office Information
                [
                    'key' => 'tab_contact_office',
                    'label' => 'Office Information',
                    'name' => 'tab_contact_office',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_contact_office_heading',
                    'label' => 'Office Section Heading',
                    'name' => 'office_heading',
                    'type' => 'text',
                    'required' => 0,
                    'default_value' => 'Head Office',
                ],
                [
                    'key' => 'field_contact_office_address',
                    'label' => 'Office Address',
                    'name' => 'office_address',
                    'type' => 'textarea',
                    'instructions' => 'HTML tags like <br> are supported',
                    'required' => 0,
                    'rows' => 3,
                    'default_value' => 'Rose Garth, Kingston Avenue,<br>Ripon, England, HG4 1TJ',
                ],
                // TAB: Contact Information
                [
                    'key' => 'tab_contact_info',
                    'label' => 'Contact Information',
                    'name' => 'tab_contact_info',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_contact_template_phone',
                    'label' => 'Phone Number',
                    'name' => 'contact_phone',
                    'type' => 'text',
                    'required' => 0,
                    'default_value' => '07555 641 081',
                ],
                [
                    'key' => 'field_contact_template_email',
                    'label' => 'Email Address',
                    'name' => 'contact_email',
                    'type' => 'email',
                    'required' => 0,
                    'default_value' => 'tomasz@emove-fs.co.uk',
                ],
                // TAB: Social Media
                [
                    'key' => 'tab_contact_social',
                    'label' => 'Social Media',
                    'name' => 'tab_contact_social',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_contact_template_social_links',
                    'label' => 'Social Links',
                    'name' => 'contact_social_links',
                    'type' => 'repeater',
                    'instructions' => 'Add social links shown in the contact page social block.',
                    'required' => 0,
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'block',
                    'button_label' => 'Add Social Link',
                    'sub_fields' => [
                        [
                            'key' => 'field_contact_template_social_link_url',
                            'label' => 'URL',
                            'name' => 'url',
                            'type' => 'url',
                            'required' => 1,
                        ],
                        [
                            'key' => 'field_contact_template_social_link_icon_class',
                            'label' => 'Icon Class',
                            'name' => 'icon_class',
                            'type' => 'font-awesome',
                        ],
                    ],
                ],
                // TAB: Contact Form
                [
                    'key' => 'tab_contact_form',
                    'label' => 'Contact Form',
                    'name' => 'tab_contact_form',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_contact_form_heading',
                    'label' => 'Form Section Heading',
                    'name' => 'contact_form_heading',
                    'type' => 'text',
                    'required' => 0,
                    'default_value' => 'Leave a message',
                ],
                [
                    'key' => 'field_contact_form_shortcode',
                    'label' => 'Contact Form Shortcode',
                    'name' => 'contact_form_shortcode',
                    'type' => 'text',
                    'instructions' => 'Shortcode for your contact form plugin (e.g., Contact Form 7)',
                    'required' => 0,
                    'default_value' => '[contact-form-7 id="98d3aa4" title="Contact"]',
                ],
                [
                    'key' => 'field_contact_form_shortcode_pl',
                    'label' => 'Contact Form Shortcode (Polish)',
                    'name' => 'contact_form_shortcode_pl',
                    'type' => 'text',
                    'instructions' => 'Shortcode for your contact form plugin (e.g., Contact Form 7)',
                    'required' => 0,
                    'default_value' => '[contact-form-7 id="a6a5a57" title="Lead from - Polski"]',
                ],
                [
                    'key' => 'field_contact_banner_video',
                    'label' => 'Bottom Banner Video',
                    'name' => 'contact_banner_video',
                    'type' => 'file',
                    'required' => 0,
                    'return_format' => 'url',
                    'mime_types' => 'mp4,mov,webm,ogg',
                ],
                [
                    'key' => 'field_contact_banner_video_poster',
                    'label' => 'Video Poster Image',
                    'name' => 'contact_banner_video_poster',
                    'type' => 'image',
                    'required' => 0,
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                ],
                [
                    'key' => 'field_contact_banner_content',
                    'label' => 'Bottom Banner Content',
                    'name' => 'contact_banner_content',
                    'type' => 'textarea',
                    'instructions' => 'Heading text shown on the bottom banner section.',
                    'required' => 0,
                    'rows' => 3,
                    'default_value' => 'We can\'t wait to hear from you!',
                ],
            ],
        ]);

        acf_add_local_field_group([
            'key' => 'group_blog',
            'title' => 'Blog Template',
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'blog-template.blade.php',
                    ],
                ],
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'blog-template',
                    ],
                ],
            ],
            'menu_order' => 6,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => [],
            'active' => true,
            'description' => '',
            'show_in_rest' => false,
            'fields' => [
                // TAB: Breadcrumbs
                [
                    'key' => 'tab_blog_breadcrumbs',
                    'label' => 'Breadcrumbs',
                    'name' => 'tab_blog_breadcrumbs',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_blog_breadcrumb_items',
                    'label' => 'Breadcrumb Items',
                    'name' => 'blog_breadcrumb_items',
                    'type' => 'repeater',
                    'instructions' => 'Optional items before the current page. Leave empty to use default breadcrumb.',
                    'required' => 0,
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => 'Add Breadcrumb Item',
                    'sub_fields' => [
                        [
                            'key' => 'field_blog_breadcrumb_item_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                            'required' => 1,
                        ],
                        [
                            'key' => 'field_blog_breadcrumb_item_url',
                            'label' => 'URL',
                            'name' => 'url',
                            'type' => 'url',
                            'required' => 0,
                        ],
                    ],
                ],
                [
                    'key' => 'field_blog_page_title',
                    'label' => 'Page Title',
                    'name' => 'blog_page_title',
                    'type' => 'text',
                    'required' => 0,
                    'default_value' => 'Blog',
                ],
                [
                    'key' => 'field_blog_posts_per_page',
                    'label' => 'Posts Per Page',
                    'name' => 'blog_posts_per_page',
                    'type' => 'number',
                    'instructions' => 'Number of posts to display per page',
                    'required' => 0,
                    'default_value' => 9,
                    'min' => 1,
                    'max' => 100,
                ],
                [
                    'key' => 'field_blog_read_more_text',
                    'label' => 'Read More Button Text',
                    'name' => 'blog_read_more_text',
                    'type' => 'text',
                    'required' => 0,
                    'default_value' => 'Read more',
                ],
                [
                    'key' => 'field_blog_no_posts_text',
                    'label' => 'No Posts Message',
                    'name' => 'blog_no_posts_text',
                    'type' => 'text',
                    'required' => 0,
                    'default_value' => 'No posts found.',
                ],
            ],
        ]);

        acf_add_local_field_group([
            'key' => 'group_privacy_policy',
            'title' => 'Privacy Policy Template',
            'location' => [
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'privacy-policy.blade.php',
                    ],
                ],
                [
                    [
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'privacy-policy',
                    ],
                ],
            ],
            'menu_order' => 7,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => [],
            'active' => true,
            'description' => '',
            'show_in_rest' => false,
            'fields' => [
                [
                    'key' => 'field_policy_page_content',
                    'label' => 'Policy Content',
                    'name' => 'policy_page_content',
                    'type' => 'wysiwyg',
                    'instructions' => 'Main content rendered on the privacy policy page.',
                    'required' => 0,
                    'toolbar' => 'full',
                    'media_upload' => 0,
                    'default_value' => '',
                    'tabs' => 'all',
                    'delay' => 1,
                ],
            ],
        ]);
    }

    private function registerOptionsPages(): void
    {
        if (! function_exists('acf_add_options_page')) {
            return;
        }

        acf_add_options_page([
            'page_title' => 'Header & Footer Settings',
            'menu_title' => 'Header & Footer Settings',
            'menu_slug' => 'header-footer-settings',
            'capability' => 'edit_posts',
            'redirect' => false,
            'position' => 58,
            'icon_url' => 'dashicons-admin-generic',
        ]);
    }

    private function registerHeaderFooterOptionsGroup(): void
    {
        acf_add_local_field_group([
            'key' => 'group_theme_header_footer',
            'title' => 'Header & Footer Settings',
            'location' => [
                [
                    [
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'header-footer-settings',
                    ],
                ],
            ],
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'fields' => [
                [
                    'key' => 'tab_hf_shared',
                    'label' => 'Shared: Phone, Email, Socials',
                    'name' => 'tab_hf_shared',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_hf_shared_phone',
                    'label' => 'Default Phone Number',
                    'name' => 'hf_shared_phone',
                    'type' => 'text',
                    'default_value' => '07555 641 081',
                ],
                [
                    'key' => 'field_hf_shared_email',
                    'label' => 'Default Email Address',
                    'name' => 'hf_shared_email',
                    'type' => 'email',
                    'default_value' => 'tomasz@emove-fs.co.uk',
                ],
                [
                    'key' => 'field_hf_shared_socials',
                    'label' => 'Social Links',
                    'name' => 'hf_shared_socials',
                    'type' => 'repeater',
                    'layout' => 'table',
                    'button_label' => 'Add Social Link',
                    'sub_fields' => [
                        [
                            'key' => 'field_hf_shared_social_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                            'default_value' => 'Facebook',
                            'wrapper' => ['width' => '25'],
                        ],
                        [
                            'key' => 'field_hf_shared_social_url',
                            'label' => 'URL',
                            'name' => 'url',
                            'type' => 'url',
                            'wrapper' => ['width' => '45'],
                        ],
                        [
                            'key' => 'field_hf_shared_social_icon',
                            'label' => 'Icon Class',
                            'name' => 'icon_class',
                            'type' => 'font-awesome',
                        ],
                    ],
                ],
                [
                    'key' => 'tab_hf_pl_header',
                    'label' => 'Polish Header',
                    'name' => 'tab_hf_pl_header',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_hf_pl_header_phone',
                    'label' => 'Phone Override',
                    'name' => 'hf_pl_header_phone',
                    'type' => 'text',
                    'instructions' => 'Optional. If empty, shared default phone is used.',
                ],
                [
                    'key' => 'field_hf_pl_header_email',
                    'label' => 'Email Override',
                    'name' => 'hf_pl_header_email',
                    'type' => 'email',
                    'instructions' => 'Optional. If empty, shared default email is used.',
                ],
                [
                    'key' => 'field_hf_pl_header_logo',
                    'label' => 'Header Logo',
                    'name' => 'hf_pl_header_logo',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'thumbnail',
                ],
                [
                    'key' => 'tab_hf_pl_footer',
                    'label' => 'Polish Footer',
                    'name' => 'tab_hf_pl_footer',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_hf_pl_footer_office_title',
                    'label' => 'Office Block Title',
                    'name' => 'hf_pl_footer_office_title',
                    'type' => 'text',
                    'default_value' => 'Head Office',
                ],
                [
                    'key' => 'field_hf_pl_footer_office_address',
                    'label' => 'Office Address',
                    'name' => 'hf_pl_footer_office_address',
                    'type' => 'textarea',
                    'instructions' => 'HTML like <br> is allowed.',
                    'rows' => 3,
                ],
                [
                    'key' => 'field_hf_pl_footer_columns',
                    'label' => 'Footer Columns',
                    'name' => 'hf_pl_footer_columns',
                    'type' => 'repeater',
                    'layout' => 'block',
                    'button_label' => 'Add Footer Column',
                    'sub_fields' => [
                        [
                            'key' => 'field_hf_pl_footer_column_title',
                            'label' => 'Column Title',
                            'name' => 'title',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_hf_pl_footer_column_links',
                            'label' => 'Links',
                            'name' => 'links',
                            'type' => 'repeater',
                            'layout' => 'table',
                            'button_label' => 'Add Link',
                            'sub_fields' => [
                                [
                                    'key' => 'field_hf_pl_footer_column_link_label',
                                    'label' => 'Label',
                                    'name' => 'label',
                                    'type' => 'text',
                                    'wrapper' => ['width' => '40'],
                                ],
                                [
                                    'key' => 'field_hf_pl_footer_column_link_url',
                                    'label' => 'URL',
                                    'name' => 'url',
                                    'type' => 'url',
                                    'wrapper' => ['width' => '60'],
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'key' => 'field_hf_pl_footer_legal',
                    'label' => 'Legal Paragraphs',
                    'name' => 'hf_pl_footer_legal',
                    'type' => 'repeater',
                    'layout' => 'block',
                    'button_label' => 'Add Paragraph',
                    'sub_fields' => [
                        [
                            'key' => 'field_hf_pl_footer_legal_text',
                            'label' => 'Paragraph',
                            'name' => 'text',
                            'type' => 'textarea',
                            'rows' => 3,
                        ],
                    ],
                ],
                [
                    'key' => 'field_hf_pl_footer_copyright',
                    'label' => 'Copyright Text',
                    'name' => 'hf_pl_footer_copyright',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_hf_pl_footer_privacy_label',
                    'label' => 'Privacy Link Label',
                    'name' => 'hf_pl_footer_privacy_label',
                    'type' => 'text',
                    'default_value' => 'Polityka prywatności',
                ],
                [
                    'key' => 'field_hf_pl_footer_privacy_url',
                    'label' => 'Privacy Link URL',
                    'name' => 'hf_pl_footer_privacy_url',
                    'type' => 'url',
                ],
                [
                    'key' => 'tab_hf_en_header',
                    'label' => 'English Header',
                    'name' => 'tab_hf_en_header',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_hf_en_header_phone',
                    'label' => 'Phone Override',
                    'name' => 'hf_en_header_phone',
                    'type' => 'text',
                    'instructions' => 'Optional. If empty, shared default phone is used.',
                ],
                [
                    'key' => 'field_hf_en_header_email',
                    'label' => 'Email Override',
                    'name' => 'hf_en_header_email',
                    'type' => 'email',
                    'instructions' => 'Optional. If empty, shared default email is used.',
                ],
                [
                    'key' => 'field_hf_en_header_logo',
                    'label' => 'Header Logo',
                    'name' => 'hf_en_header_logo',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'thumbnail',
                ],
                [
                    'key' => 'tab_hf_en_footer',
                    'label' => 'English Footer',
                    'name' => 'tab_hf_en_footer',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_hf_en_footer_office_title',
                    'label' => 'Office Block Title',
                    'name' => 'hf_en_footer_office_title',
                    'type' => 'text',
                    'default_value' => 'Head Office',
                ],
                [
                    'key' => 'field_hf_en_footer_office_address',
                    'label' => 'Office Address',
                    'name' => 'hf_en_footer_office_address',
                    'type' => 'textarea',
                    'instructions' => 'HTML like <br> is allowed.',
                    'rows' => 3,
                ],
                [
                    'key' => 'field_hf_en_footer_columns',
                    'label' => 'Footer Columns',
                    'name' => 'hf_en_footer_columns',
                    'type' => 'repeater',
                    'layout' => 'block',
                    'button_label' => 'Add Footer Column',
                    'sub_fields' => [
                        [
                            'key' => 'field_hf_en_footer_column_title',
                            'label' => 'Column Title',
                            'name' => 'title',
                            'type' => 'text',
                        ],
                        [
                            'key' => 'field_hf_en_footer_column_links',
                            'label' => 'Links',
                            'name' => 'links',
                            'type' => 'repeater',
                            'layout' => 'table',
                            'button_label' => 'Add Link',
                            'sub_fields' => [
                                [
                                    'key' => 'field_hf_en_footer_column_link_label',
                                    'label' => 'Label',
                                    'name' => 'label',
                                    'type' => 'text',
                                    'wrapper' => ['width' => '40'],
                                ],
                                [
                                    'key' => 'field_hf_en_footer_column_link_url',
                                    'label' => 'URL',
                                    'name' => 'url',
                                    'type' => 'url',
                                    'wrapper' => ['width' => '60'],
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'key' => 'field_hf_en_footer_legal',
                    'label' => 'Legal Paragraphs',
                    'name' => 'hf_en_footer_legal',
                    'type' => 'repeater',
                    'layout' => 'block',
                    'button_label' => 'Add Paragraph',
                    'sub_fields' => [
                        [
                            'key' => 'field_hf_en_footer_legal_text',
                            'label' => 'Paragraph',
                            'name' => 'text',
                            'type' => 'textarea',
                            'rows' => 3,
                        ],
                    ],
                ],
                [
                    'key' => 'field_hf_en_footer_copyright',
                    'label' => 'Copyright Text',
                    'name' => 'hf_en_footer_copyright',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_hf_en_footer_privacy_label',
                    'label' => 'Privacy Link Label',
                    'name' => 'hf_en_footer_privacy_label',
                    'type' => 'text',
                    'default_value' => 'Privacy Policy',
                ],
                [
                    'key' => 'field_hf_en_footer_privacy_url',
                    'label' => 'Privacy Link URL',
                    'name' => 'hf_en_footer_privacy_url',
                    'type' => 'url',
                ],
            ],
        ]);
    }
}
